version: '3.2'

services:
  backend:
    container_name: backend
    platform: linux/amd64
    image: node:14.5.0-alpine
    tty: true
    command: sh -c "cd /var/www && npm install && npm start"
    volumes:
      - ./backend:/var/www
    ports:
      - 8080:8080
  frontend:
    container_name: frontend
    platform: linux/amd64
    image: node:16.3.0-alpine
    command: sh -c "cd /var/www && npm install && npm run build && npm install -g serve && serve -s build"
    tty: true
    volumes:
      - ./frontend:/var/www
    ports:
      - 3000:3000
